name: CI Backend

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  ci-backend:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.7'

    - name: Set up PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/src" >> $GITHUB_ENV

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Install llmax in editable mode
      run: poetry install --no-root

    - name: Run Ruff
      run: |
        poetry run ruff check --preview

    - name: Run Pyright
      run: |
        poetry run pyright .

    - name: Run MyPy
      run: |
        poetry run mypy .

    - name: Run Unit Tests
      run: |
        poetry run pytest --cov-report=term-missing

    - name: Set Output if Push to Main
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: echo "::set-output name=push_to_main::true"